# Assignment 1 IRS

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [2]:
# required imports
import pandas as pd
import numpy as np
import fnmatch
import os

Suppose we have 3 files containing data :

### File Contents

<img src="1.png"/>
<img src="2.png"/>
<img src="3.png"/>

# Step 1 Create Files with Dummy data

#You have to create few files with dummy data of your own choice as shown above


# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [11]:
# Here we have intialized some variables, you can add more if required.

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set


In [12]:
#Your code starts here   
path = os.walk("C:/Users/tehre/Desktop/This/AI/IRS/myFiles")
i=1
for root,directories, files in path:
    for file in files:
        files_dict[i] = file;
        i+=1
print(files_dict)
#Your code ends here       

{1: 'f1.txt', 2: 'f2.txt', 3: 'f3.txt'}


Displaying the count of files.

In [13]:
for key in files_dict:
    file_count+=1
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 3


Displaying Dictionary containing all files.

In [14]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {1: 'f1.txt', 2: 'f2.txt', 3: 'f3.txt'}


# Step 3 Extract Unique Vocabulary

In [112]:
#write code to print all the unique words in every file and store them in a set

In [15]:
#Your code starts here    
for key in files_dict:
    text_file = open(files_dict[key], 'r')
    text = text_file.read()
    text = text.strip(",.")
    text_file.close()
    #cleaning
    text = text.lower()
    words = text.split()
    for word in words:
            unique_word_set.add(word)
print("Dictionary of unique words: ",unique_word_set)
#Your code ends here

Dictionary of unique words:  {'my', 'very', 'pen', 'book', 'this', 'is', 'interesting'}


### Expected Output

<img src="4.png"/>

# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

In [71]:
# Create Term doc matrix such that columns will be unique words and all the files will be rows

# Write code to count all the unique words appearances in all the files and store it in a dictionary for words


In [21]:
#Your code starts here

TDM = np.zeros(( len(files_dict),len(unique_word_set)))
print("Term document matrix initially\n",TDM)

dic_of_words ={}
for word in unique_word_set:
    count =0
    for file in files_dict:
        text_file = open(files_dict[file], 'r')
        text = text_file.read()
        text = text.lower()
        text = text.strip(",.!''")
        words = text.split()
        count +=words.count(word)
    dic_of_words[word] = count

print("\nDictionary of words")
print(dic_of_words)
#Your code ends here

Term document matrix initially
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

Dictionary of words
{'my': 3, 'very': 1, 'pen': 1, 'book': 2, 'this': 2, 'is': 3, 'interesting': 1}


### Expected Output

<img src="5.png"/>

# Step 5 Fill Term Document Matrix

In [157]:
# Fill the term doc matrix by checking if the unique word exists in a file or not
# If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
# Do the same for all the files present in the directory



In [22]:
#Your code starts here    
for file in files_dict:
    text_file = open(files_dict[file], 'r')
    text = text_file.read()
    text = text.lower()
    text= text.strip(",.!''")
    words = text.split()
    i = 0 
    for word in unique_word_set:
        if word in words:
            TDM[file-1][i] = 1
        else:
            TDM[file-1][i] = 0
        i+=1
print("Term Document Matrix after filling\n",TDM)

#Your code ends here

Term Document Matrix after filling
 [[1. 0. 0. 1. 1. 1. 0.]
 [1. 0. 1. 0. 1. 1. 0.]
 [1. 1. 0. 1. 0. 1. 1.]]


### Expected Output

<img src="6.png"/>

# Step 6 Ask for a user Query

In [ ]:
# For user query make a column vector of length of all the unique words present in a set

In [25]:
#Your code starts here    
x = np.zeros((len(unique_word_set),1));

print("column vector initially\n",x)
#Your code ends here

column vector initially
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### Expected Output

<img src="7.png"/>

In [27]:
query = input("\nWrite something for searching  ")
# Check every word of query if it exists in the set of unique words or not
# If exists then increment the count of that word in column vector


Write something for searching  book interesting


In [28]:
#Your code starts here  
query_words = query.split();
set_of_unique_words = list(unique_word_set)
for unique_word in set_of_unique_words:
    if unique_word in query_words:
        x[set_of_unique_words.index(unique_word)] = 1
    #if unique_word in query_words:
    
print(x)
#Your code ends here

[[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]]


### Expected Output

<img src="8.png"/>

# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [29]:
#Your code starts here  
resultant_vector = np.dot(TDM,x)
max = np.max(resultant_vector)
result = np. where(resultant_vector == max)
print(resultant_vector)
print("Maximum in resultant is: ", max)
result = resultant_vector.tolist().index(max)
print("Index of maximum resultant is: ",result)
#Your code ends here

[[1.]
 [0.]
 [2.]]
Maximum in resultant is:  2.0
Index of maximum resultant is:  2


### Expected Output

<img src="9.png"/>

# Step 8 Display the contents of file


In [ ]:
#Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [30]:
#Your code starts here    
text_file = open(files_dict[result], 'r')
text = text_file.read()
print(text)
#Your code ends here

This is my pen

                                                                                                                                                                                                                                          


Congratulations Now you are able to build your own small IRS.